Auth and issue testing
SwagLyrics/swaglyrics-backend pull request #18
Opened 2020-01-21 17:50 UTC by dhrumilp15

2020-01-21 17:50 UTC, pep8speaks commented
Hello @dhrumilp15! Thanks for opening this PR. 

* In the file [`auth.py`](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py):

> [Line 3:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'Crypto.PublicKey.RSA' imported but unused
> [Line 7:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L7): [F401](https://duckduckgo.com/?q=pep8%20F401) 'json' imported but unused
> [Line 18:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L18): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 30:27](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L30): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 32:14](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L32): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 32:21](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L32): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 33:14](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L33): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 34:14](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L34): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 37:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L37): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 40:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L40): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 51:16](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L51): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 51:18](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L51): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 52:28](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L52): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 53:21](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L53): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 56:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L56): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 64:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L64): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 69:17](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L69): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'expiry_time'
> [Line 74:16](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L74): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'token'
> [Line 76:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L76): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 84:27](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L84): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 88:16](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L88): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 88:18](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L88): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 89:28](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L89): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 90:21](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L90): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 95:25](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L95): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 97:16](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L97): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 97:18](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L97): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 98:28](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L98): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 99:21](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L99): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 105:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L105): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 113:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L113): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 114:5](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L114): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'res' is assigned to but never used
> [Line 114:25](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L114): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 116:16](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L116): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 116:18](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L116): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 117:28](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L117): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 118:21](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L118): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 121:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575ccabbe44e3/auth.py#L121): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 122:17](https://github.com/SwagLyrics/swaglyrics-backend/blob/214b78f4aea8a685861480af45d575c [...]

2020-01-21 18:41 UTC, aadibajpai commented
> Hello @dhrumilp15! Thanks for updating this PR.
> 
> * In the file [`test_auth.py`](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py):
> 
> > [Line 1:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'unittest' imported but unused
> > [Line 3:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L3): [F403](https://duckduckgo.com/?q=pep8%20F403) 'from auth import *' used; unable to detect undefined names
> > [Line 7:24](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L7): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> > [Line 7:26](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L7): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> > [Line 9:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L9): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 10:12](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L10): [F405](https://duckduckgo.com/?q=pep8%20F405) 'authenticate_github_app' may be undefined, or defined from star imports: auth
> > [Line 10:49](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L10): [F405](https://duckduckgo.com/?q=pep8%20F405) 'auth' may be undefined, or defined from star imports: auth
> > [Line 12:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L12): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> > [Line 12:31](https://github.com/SwagLyrics/swaglyrics-backend/blob/9ac40293d2ad0b9bebddd95f536a832e8de6f868/test_auth.py#L12): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> 
> ##### Comment last updated at 2020-01-21 18:30:25 UTC

Please take care of these, also, please add the auth functions to the utils file

2020-01-22 01:30 UTC, dhrumilp15 commented
Hey! I'm still working on the tests, but as future features are implemented, wouldn't the utils file become too large and unwieldy? Are there future plans to better split the codebase?

2020-01-22 02:18 UTC, aadibajpai commented
> Hey! I'm still working on the tests, but as future features are implemented, wouldn't the utils file become too large and unwieldy? Are there future plans to better split the codebase?

Well the utils file houses all utility functions so it is appropriate here. Yeah we might branch off files as the need arises but it should be ok for now.

2020-01-23 05:25 UTC, dhrumilp15 commented
There were pep8 style errors due to the walrus operator in python 3.8, so I rewrote the if statement to not cause pep8 warnings in utils.py.

2020-01-23 07:17 UTC, aadibajpai commented
> There were pep8 issues due to the walrus operator in python 3.8, so I rewrote the if statement to not cause pep8 issues in utils.py.

Don't edit the code you're not modifying please :)

I _think_ pep8 is configured to only review the diffs so it will be easier for me to review your PR if it only contains changes relevant to the purpose of your PR 🙂

2020-01-23 07:46 UTC, aadibajpai commented on issue_maker.py
> +    bearer = "token %s" % token
why not use fstrings :)

2020-01-23 19:47 UTC, aadibajpai requested changes
Please do not modify code you're not adding or removing :)

Pep8 should apply to the code you're adding, we follow max character limit of 120 chars btw.

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +                              username=username,
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +    headers = {
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +    if t_expiry + 3600 - \
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +    r = requests.get(
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +                print(
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +    lyrics = Lyrics.query.filter(
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +            return json.dumps(
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +            return json.dumps(
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on issue_maker.py
> +        return 'Updated PythonAnywhere server to commit {commit}'.format(
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on utils.py
> +                if not (request.headers.get('CF-Connecting-IP')):
Please do not modify code you're not adding or removing :)

2020-01-23 19:47 UTC, aadibajpai commented on utils.py
> +                    print(
Please do not modify code you're not adding or removing :)

2020-01-23 20:00 UTC, aadibajpai commented on issue_maker.py
> +    r = requests.post(
Please do not modify code you're not adding or removing :)

2020-01-23 20:01 UTC, aadibajpai commented on utils.py
> +repo_url = "https://api.github.com/repos/dhrumilp15/swaglyrics-backend/"
You probably need to change this

2020-01-24 02:18 UTC, dhrumilp15 commented
I've written tests and moved the auth code over to utils.py!

2020-01-24 02:38 UTC, aadibajpai commented
> I've written tests and moved the auth code over to utils.py!

I don't think you've taken care of my last review 🙂

2020-01-24 04:49 UTC, closed without merging